-- Add missing columns to exams table for all settings

-- Basic Settings
ALTER TABLE exams ADD COLUMN IF NOT EXISTS introduction TEXT;

-- Question Settings
ALTER TABLE exams ADD COLUMN IF NOT EXISTS pagination_type VARCHAR(20) DEFAULT 'all';
ALTER TABLE exams ADD COLUMN IF NOT EXISTS allow_blank_answers BOOLEAN DEFAULT TRUE;

-- Review Settings
ALTER TABLE exams ADD COLUMN IF NOT EXISTS conclusion_text TEXT;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS show_custom_result_message BOOLEAN DEFAULT FALSE;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS pass_message TEXT;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS fail_message TEXT;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS passing_score INTEGER DEFAULT 60;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS show_score BOOLEAN DEFAULT TRUE;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS show_test_outline BOOLEAN DEFAULT TRUE;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS show_correct_incorrect BOOLEAN DEFAULT TRUE;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS show_correct_answer BOOLEAN DEFAULT TRUE;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS show_explanation BOOLEAN DEFAULT TRUE;

-- Access Control
ALTER TABLE exams ADD COLUMN IF NOT EXISTS access_type VARCHAR(20) DEFAULT 'anyone';
ALTER TABLE exams ADD COLUMN IF NOT EXISTS access_passcode VARCHAR(100);
ALTER TABLE exams ADD COLUMN IF NOT EXISTS identifier_list TEXT[] DEFAULT '{}';
ALTER TABLE exams ADD COLUMN IF NOT EXISTS email_list TEXT[] DEFAULT '{}';
ALTER TABLE exams ADD COLUMN IF NOT EXISTS time_limit_type VARCHAR(20) DEFAULT 'unlimited';
ALTER TABLE exams ADD COLUMN IF NOT EXISTS attempt_limit_type VARCHAR(20) DEFAULT 'unlimited';
ALTER TABLE exams ADD COLUMN IF NOT EXISTS max_attempts INTEGER DEFAULT 1;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS identifier_prompt VARCHAR(255) DEFAULT 'Enter your name';

-- Browser Settings
ALTER TABLE exams ADD COLUMN IF NOT EXISTS disable_right_click BOOLEAN DEFAULT FALSE;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS disable_copy_paste BOOLEAN DEFAULT FALSE;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS disable_translate BOOLEAN DEFAULT FALSE;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS disable_autocomplete BOOLEAN DEFAULT FALSE;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS disable_spellcheck BOOLEAN DEFAULT FALSE;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS disable_printing BOOLEAN DEFAULT FALSE;
